### ISSUE TITLE
why is there a green-fagging option for an _uploader_?

### ISSUE THREAD

**Issue by 74togo** [RealDolos/volaupload#1]

**Comment by RealDolos** [comment]
why not?

**Comment by 74togo** [comment]
Because it encourages your users to put their password in plaintext in their home directory, or type it out unhidden on their screen

**Comment by RealDolos** [comment]
so? Not like they type the password in the webbrowser. If you can steal file from home or watch users typing in password, you can steal the same passwords from the browser (password db or while typing)

**Comment by 74togo** [comment]
but people actually have a purpose to login on their browser. Authenticated chat.

**Comment by RealDolos** [comment]
And uploaders have reasons too: Authenticated uploads (should lain ever make that visible) and upload stats. Now literally kill yourself @PhearTheCeal
