### ISSUE TITLE
Works only 30% of the time.

### ISSUE THREAD

**Issue by nickhero** [RealDolos/volaupload#4]
Not sure, if this repository is even still looked at, but i was searching for a volafile uploader from the command line. 
Sadly the tool only works 20-30% of the time, with even varying results when executing the same command. When uploading a file i usually get the answer:
`Starting DoS...
Failure to fly: Can't convert 'int' object to str implicitly (<class 'TypeError'>)
All done in 0.00secs (0.00MB/s)`
At the same time though it actually sometimes works, even if no parameters change which is the weird thing about it. This is running on debian 9 stretch. If you cant help me out, I would greatly appreciate it if you could point me towards another solution to uploading files over the terminal. Thanks!

**Comment by RealDolos** [comment]
The python uploader is abandoned. Use the node uploader instead (and file issues there).
https://github.com/RealDolos/node-volaupload
